sloc/urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('horai.sloc.views',
    (r'^/$', 'index'),

    (r'^/segment/(?P<segment_id>\d+)/detail$', 'segment_detail'),
    (r'^/segment/(?P<segment_id>\d+)/detail/segment.csv$', 'segment_detail_csv'),

    (r'^/language/(?P<language_id>\d+)/detail$', 'language_detail'),
    (r'^/language/(?P<language_id>\d+)/detail/language.csv$', 'language_detail_csv'),

    (r'^/add$', 'sloc_add'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^sloc', include('horai.sloc.urls')),
    (r'^sloc/admin/', include(admin.site.urls)),
)

sloc/models.py
from django.db import models

class Segment(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    branch = models.CharField(max_length=200)
    directory_path_used = models.CharField(max_length=200)
    def __unicode__(self):
        return u"%s (%s)" % (unicode(self.name),unicode(self.branch))

class Language(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    def __unicode__(self):
        return u"%s (%s)" % (unicode(self.name),unicode(self.description))

class SlocType(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    def __unicode__(self):
        return u"%s" % (unicode(str(self.name)))

class Sloc(models.Model):
    source_lines_of_code = models.IntegerField()
    generated_date = models.DateTimeField('date generated')
    created_date = models.DateTimeField(auto_now=True, editable=False)
    segment = models.ForeignKey(Segment)
    language = models.ForeignKey(Language)
    reported_by = models.CharField(max_length=200)
    sloc_type = models.ForeignKey(SlocType)
    def __unicode__(self):
        return u"%s" % (unicode(str(self.source_lines_of_code)))

sloc/forms.py
from django import forms
from models import Segment, Language, SlocType
from datetime import date

class SlocForm(forms.Form):
    sloc = forms.IntegerField(required=True)
    segment = forms.ModelChoiceField(Segment.objects.all(),required=True)
    language = forms.ModelChoiceField(Language.objects.all(),required=True)
    generated_date = forms.DateField(initial=date.today(),required=True)
    reported_by = forms.CharField(max_length=100,required=True)
    sloc_type = forms.ModelChoiceField(SlocType.objects.all(),required=True)

sloc/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from models import Segment, Language, Sloc, SlocType
from forms import SlocForm

def index(request):
    segments = Segment.objects.all()
    languages = Language.objects.all()
    return render_to_response('sloc/index.html', {'segments': segments, 'languages': languages})

def segment_detail(request, segment_id):
    segment = get_object_or_404(Segment, pk=segment_id)
    slocs = Sloc.objects.filter(segment=segment_id).order_by('-created_date')[:20]
    return render_to_response('sloc/segment_detail.html', {'segment': segment, 'slocs': slocs})

def segment_detail_csv(request, segment_id):
    segment = get_object_or_404(Segment, pk=segment_id)
    slocs = Sloc.objects.filter(segment=segment_id)
    return render_to_response('sloc/segment_detail.csv', {'segment': segment, 'slocs': slocs})

def language_detail(request, language_id):
    language = get_object_or_404(Language, pk=language_id)
    slocs = Sloc.objects.filter(language=language_id).order_by('-created_date')[:20]
    return render_to_response('sloc/language_detail.html', {'language': language, 'slocs': slocs})

def language_detail_csv(request, language_id):
    language = get_object_or_404(Language, pk=language_id)
    slocs = Sloc.objects.filter(language=language_id)
    return render_to_response('sloc/language_detail.csv', {'language': language, 'slocs': slocs})

def sloc_add(request):
    def errorHandle(error):
        form = SlocForm()
        return render_to_response('sloc/sloc_add.html', {
                'error' : error,
                'form' : form,
        })
    if request.method == 'POST':
        form = SlocForm(request.POST)
        if form.is_valid():
            sloc = form.cleaned_data['sloc']
            segment = form.cleaned_data['segment']
            language = form.cleaned_data['language']
            generated_date = form.cleaned_data['generated_date']
            reported_by = form.cleaned_data['reported_by']
            sloc_type = form.cleaned_data['sloc_type']
            new_sloc = Sloc(source_lines_of_code=sloc, segment=segment,
                language=language, generated_date=generated_date, reported_by=reported_by, sloc_type=sloc_type)
            
            new_sloc.save()

            if new_sloc:
                error = u'Sloc successfully saved'
                return errorHandle(error)
            else:
                error = u'Could not save sloc entry'
                return errorHandle(error)
        else:
            error = u'The form is not filled in correctly (are all fields filled in?)'
            return errorHandle(error)
    else:
        form = SlocForm()
        return render_to_response('sloc/sloc_add.html', {'form': form})

templates/base.html
<html>
    <head>
        <title>SLOC tracker - {% block title %}{% endblock %}</title>
    </head>
    <body>
        <h1>SLOC tracker</h1>
        <hr />
        {% block content %}{% endblock %}
        <hr />
        <a href="/sloc">Main page</a> | <a href="/sloc/add">Manually enter a new SLOC value</a> | <a href="/sloc/admin">Site admin</a>
    </body>
</html>

templates/sloc/index.html
{% extends "base.html" %}
{% block content %}
<h2>Segments</h2>
{% if segments %}
<ul>
    {% for segment in segments %}
    <li><a href="/sloc/segment/{{ segment.id }}/detail">{{ segment.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No segments are available.</p>
{% endif %}
<h2>Languages</h2>
{% if languages %}
<ul>
    {% for language in languages %}
    <li><a href="/sloc/language/{{ language.id }}/detail">{{ language.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No languages are available.</p>
{% endif %}
{% endblock %}

templates/sloc/language_detail.html
{% extends "base.html" %}
{% block title %}Details for {{ language.name }}{% endblock %}
{% block content %}
<h2>Details for {{ language.name }}</h2>
<div>
    <ul>
        <li><b>Description:</b> "{{ language.description }}"</li>
        <li><b>CSV Export:</b> <a href="{% url sloc.views.language_detail language.id %}/language.csv">click here to download</a></li>
    </ul>
</div>

<h3>Sloc History</h3>
<span>This is limited to 20 of the most recent SLOCs that have been reported. Use a CSV export to download all known SLOC entries.</span>
{% if slocs %}
    <ul>
    {% for sloc in slocs %}
        <li>For "{{ sloc.generated_date.date}}", an sloc of "{{ sloc.source_lines_of_code }}" ("{{sloc.sloc_type}}") was reported for the "{{ sloc.segment }}" segment by "{{ sloc.reported_by }}" on "{{ sloc.created_date }}".</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No slocs are available for this language.</p>
{% endif %}
{% endblock %}

templates/sloc/segment_detail.html
{% extends "base.html" %}
{% block title %}Details for {{ segment.name }}{% endblock %}
{% block content %}
<h2>Details for {{ segment.name }}</h2>
<div>
    <ul>
        <li><b>Description:</b> "{{ segment.description }}"</li>
        <li><b>Directory path used:</b> "{{ segment.directory_path_used }}"</li>
        <li><b>Branch:</b> "{{ segment.branch }}"</li>
        <li><b>CSV Export:</b> <a href="{% url sloc.views.segment_detail segment.id %}/segment.csv">click here to download</a></li>
    </ul>
</div>

<h3>Sloc History</h3>
<span>This is limited to 20 of the most recent SLOCs that have been reported. Use a CSV export to download all known SLOC entries.</span>
{% if slocs %}
    <ul>
    {% for sloc in slocs %}
        <li>For "{{ sloc.generated_date.date}}", an sloc of "{{ sloc.source_lines_of_code }}" ("{{sloc.sloc_type}}") was reported for the "{{ sloc.language }}" language by "{{ sloc.reported_by }}" on "{{ sloc.created_date }}".</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No slocs are available for this segment.</p>
{% endif %}
{% endblock %}

templates/sloc/sloc_add.html
{% extends "base.html" %}
{% block title %}Add new sloc entry{% endblock %}
{% block content %}
<h2>Add a new sloc entry</h2>
<p style="color:red;">{{ error }}</p>
<style>div{padding-bottom:5px;}</style>
<form action="/sloc/add" method="POST">
    <div class="fieldWrapper">
        {{ form.sloc.errors }}
        <label for="id_sloc">Source Lines of Code (must be an integer):</label><br />
        {{ form.sloc }}
    </div>
    <div class="fieldWrapper">
        {{ form.language.errors }}
        <label for="id_language">Programming Language:</label><br />
        {{ form.language }}
    </div>
    <div class="fieldWrapper">
        {{ form.segment.errors }}
        <label for="id_segment">Segment:</label><br />
        {{ form.segment }}
    </div>
    <div class="fieldWrapper">
       {{ form.sloc_type.errors }}
       <label for="sloc_type">Type of SLOC:</label><br />
       {{ form.sloc_type }}
    </div>
    <div class="fieldWrapper">
        {{ form.generated_date.errors }}
        <label for="id_segment">Date the sloc data is for (must be in yyyy-mm-dd form):</label><br />
        {{ form.generated_date }}
    </div>
    <div class="fieldWrapper">
        {{ form.reported_by.errors }}
        <label for="id_reported_by">Reported by:</label><br />
        {{ form.reported_by }}
    </div>
    <p><input type="submit" value="Submit"></p>
</form>
{% endblock %}